INFO 2023-07-27 16:24:13,926 autoreload 12192 12100 Watching for file changes with StatReloader
INFO 2023-07-27 16:25:19,790 autoreload 12192 12100 K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py changed, reloading.
INFO 2023-07-27 16:25:20,712 autoreload 6332 13036 Watching for file changes with StatReloader
INFO 2023-07-27 16:25:27,139 views 6332 14584 Index page accessed
INFO 2023-07-27 16:25:27,140 basehttp 6332 14584 "GET / HTTP/1.1" 200 178
WARNING 2023-07-27 16:25:28,051 log 6332 14584 Not Found: /favicon.ico
WARNING 2023-07-27 16:25:28,054 basehttp 6332 14584 "GET /favicon.ico HTTP/1.1" 404 2966
INFO 2023-07-27 16:25:43,130 basehttp 6332 14584 "GET /about HTTP/1.1" 301 0
INFO 2023-07-27 16:25:43,139 views 6332 12964 About page accessed
INFO 2023-07-27 16:25:43,141 basehttp 6332 12964 "GET /about/ HTTP/1.1" 200 159
INFO 2023-07-29 11:05:07,420 autoreload 136 2412 Watching for file changes with StatReloader
INFO 2023-07-29 11:05:55,619 autoreload 13008 13648 Watching for file changes with StatReloader
INFO 2023-07-29 11:09:10,653 autoreload 13008 13648 K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py changed, reloading.
INFO 2023-07-29 11:09:19,707 autoreload 2296 904 Watching for file changes with StatReloader
INFO 2023-07-29 11:10:20,229 autoreload 2296 904 K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py changed, reloading.
INFO 2023-07-29 11:10:21,523 autoreload 896 11288 Watching for file changes with StatReloader
INFO 2023-07-29 11:10:37,675 views 896 12140 Index page accessed
INFO 2023-07-29 11:10:37,700 basehttp 896 12140 "GET / HTTP/1.1" 200 178
WARNING 2023-07-29 11:10:43,575 log 896 12140 Not Found: /favicon.ico
WARNING 2023-07-29 11:10:43,575 basehttp 896 12140 "GET /favicon.ico HTTP/1.1" 404 2966
ERROR 2023-07-29 11:10:55,649 log 896 9540 Internal Server Error: /headsortails/
Traceback (most recent call last):
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py", line 12, in headsortails
    coin = choice['Орёл', 'Решка']
           ~~~~~~^^^^^^^^^^^^^^^^^
TypeError: 'method' object is not subscriptable
ERROR 2023-07-29 11:10:55,653 basehttp 896 9540 "GET /headsortails/ HTTP/1.1" 500 66629
INFO 2023-07-29 11:14:28,271 autoreload 896 11288 K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py changed, reloading.
INFO 2023-07-29 11:14:32,973 autoreload 9136 11824 Watching for file changes with StatReloader
INFO 2023-07-29 11:14:39,323 views 9136 4724 getting Решка
INFO 2023-07-29 11:14:39,324 views 9136 4724 В базу данных добавлена запись: Toss result: Решка, time: 11:14:38.948938
INFO 2023-07-29 11:14:39,326 basehttp 9136 4724 "GET /headsortails/ HTTP/1.1" 200 95
INFO 2023-07-29 11:15:11,382 views 9136 6308 getting Орёл
INFO 2023-07-29 11:15:11,382 views 9136 6308 В базу данных добавлена запись: Toss result: Орёл, time: 11:15:11.270834
INFO 2023-07-29 11:15:11,383 basehttp 9136 6308 "GET /headsortails/ HTTP/1.1" 200 95
INFO 2023-07-29 11:15:15,272 views 9136 6308 getting Орёл
INFO 2023-07-29 11:15:15,272 views 9136 6308 В базу данных добавлена запись: Toss result: Орёл, time: 11:15:15.189928
INFO 2023-07-29 11:15:15,273 basehttp 9136 6308 "GET /headsortails/ HTTP/1.1" 200 95
INFO 2023-07-29 11:15:16,656 views 9136 11220 getting Решка
INFO 2023-07-29 11:15:16,656 views 9136 11220 В базу данных добавлена запись: Toss result: Решка, time: 11:15:16.569988
INFO 2023-07-29 11:15:16,657 basehttp 9136 11220 "GET /headsortails/ HTTP/1.1" 200 95
INFO 2023-07-29 11:15:53,291 autoreload 9136 11824 K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py changed, reloading.
INFO 2023-07-29 11:15:54,224 autoreload 7864 11204 Watching for file changes with StatReloader
INFO 2023-07-29 11:15:57,309 views 7864 2412 getting Орёл
INFO 2023-07-29 11:15:57,309 views 7864 2412 В базу данных добавлена запись: Toss result: Орёл, time: 11:15:57.221534
INFO 2023-07-29 11:15:57,311 basehttp 7864 2412 "GET /headsortails/ HTTP/1.1" 200 27
INFO 2023-07-29 11:19:55,254 autoreload 10396 10644 Watching for file changes with StatReloader
INFO 2023-07-29 11:19:59,442 views 10396 12884 Index page accessed
INFO 2023-07-29 11:19:59,443 basehttp 10396 12884 "GET / HTTP/1.1" 200 178
INFO 2023-07-29 11:20:09,069 views 10396 7900 getting Орёл
INFO 2023-07-29 11:20:09,069 views 10396 7900 В базу данных добавлена запись: Toss result: Орёл, time: 11:20:08.941801
INFO 2023-07-29 11:20:09,070 basehttp 10396 7900 "GET /headsortails/ HTTP/1.1" 200 27
INFO 2023-07-29 13:30:50,695 autoreload 14648 15648 Watching for file changes with StatReloader
INFO 2023-07-29 13:30:59,838 views 14648 9620 Index page accessed
INFO 2023-07-29 13:30:59,840 basehttp 14648 9620 "GET / HTTP/1.1" 200 178
INFO 2023-07-29 13:31:08,197 views 14648 9620 getting Орёл
INFO 2023-07-29 13:31:08,197 views 14648 9620 В базу данных добавлена запись: Toss result: Орёл, time: 13:31:07.944387
ERROR 2023-07-29 13:31:08,854 log 14648 9620 Internal Server Error: /headsortails/
Traceback (most recent call last):
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py", line 17, in headsortails
    return HttpResponse(f'На монете: {coin}\n\n{coin_toss.statistics(5)}')
                                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\models.py", line 17, in statistics
    if all_tosses[i].toss == 'Орёл':
       ~~~~~~~~~~^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\db\models\query.py", line 432, in __getitem__
    return self._result_cache[k]
           ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
ERROR 2023-07-29 13:31:08,859 basehttp 14648 9620 "GET /headsortails/ HTTP/1.1" 500 75751
INFO 2023-07-29 13:32:00,255 autoreload 14648 15648 K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\models.py changed, reloading.
INFO 2023-07-29 13:32:01,402 autoreload 13332 13152 Watching for file changes with StatReloader
INFO 2023-07-29 13:32:04,648 views 13332 9184 getting Орёл
INFO 2023-07-29 13:32:04,650 views 13332 9184 В базу данных добавлена запись: Toss result: Орёл, time: 13:32:04.550015
INFO 2023-07-29 13:32:04,652 basehttp 13332 9184 "GET /headsortails/ HTTP/1.1" 200 54
INFO 2023-07-29 13:32:16,486 views 13332 8216 getting Решка
INFO 2023-07-29 13:32:16,488 views 13332 8216 В базу данных добавлена запись: Toss result: Решка, time: 13:32:16.371297
INFO 2023-07-29 13:32:16,490 basehttp 13332 8216 "GET /headsortails/ HTTP/1.1" 200 56
INFO 2023-07-29 13:32:25,396 views 13332 14308 getting Орёл
INFO 2023-07-29 13:32:25,397 views 13332 14308 В базу данных добавлена запись: Toss result: Орёл, time: 13:32:25.295202
INFO 2023-07-29 13:32:25,400 basehttp 13332 14308 "GET /headsortails/ HTTP/1.1" 200 54
INFO 2023-07-29 13:32:34,615 views 13332 13600 getting Орёл
INFO 2023-07-29 13:32:34,616 views 13332 13600 В базу данных добавлена запись: Toss result: Орёл, time: 13:32:34.527088
INFO 2023-07-29 13:32:34,618 basehttp 13332 13600 "GET /headsortails/ HTTP/1.1" 200 54
INFO 2023-07-29 13:32:38,025 views 13332 13600 getting Орёл
INFO 2023-07-29 13:32:38,025 views 13332 13600 В базу данных добавлена запись: Toss result: Орёл, time: 13:32:37.937604
INFO 2023-07-29 13:32:38,028 basehttp 13332 13600 "GET /headsortails/ HTTP/1.1" 200 54
INFO 2023-07-29 13:33:30,777 autoreload 13332 13152 K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py changed, reloading.
INFO 2023-07-29 13:33:31,774 autoreload 5944 13212 Watching for file changes with StatReloader
INFO 2023-07-29 13:33:34,283 views 5944 2876 getting Орёл
INFO 2023-07-29 13:33:34,284 views 5944 2876 В базу данных добавлена запись: Toss result: Орёл, time: 13:33:34.202465
INFO 2023-07-29 13:33:34,286 basehttp 5944 2876 "GET /headsortails/ HTTP/1.1" 200 54
INFO 2023-07-29 13:33:37,226 views 5944 2876 getting Орёл
INFO 2023-07-29 13:33:37,226 views 5944 2876 В базу данных добавлена запись: Toss result: Орёл, time: 13:33:37.142363
INFO 2023-07-29 13:33:37,229 basehttp 5944 2876 "GET /headsortails/ HTTP/1.1" 200 54
INFO 2023-07-29 13:33:43,185 views 5944 9620 getting Решка
INFO 2023-07-29 13:33:43,186 views 5944 9620 В базу данных добавлена запись: Toss result: Решка, time: 13:33:43.081856
INFO 2023-07-29 13:33:43,188 basehttp 5944 9620 "GET /headsortails/ HTTP/1.1" 200 56
INFO 2023-07-29 13:33:46,778 views 5944 9620 getting Решка
INFO 2023-07-29 13:33:46,779 views 5944 9620 В базу данных добавлена запись: Toss result: Решка, time: 13:33:46.696798
INFO 2023-07-29 13:33:46,781 basehttp 5944 9620 "GET /headsortails/ HTTP/1.1" 200 56
INFO 2023-08-01 21:34:54,119 autoreload 10328 5588 Watching for file changes with StatReloader
INFO 2023-08-01 21:35:43,061 views 10328 1812 Index page accessed
INFO 2023-08-01 21:35:43,200 basehttp 10328 1812 "GET / HTTP/1.1" 200 363
WARNING 2023-08-01 21:35:45,924 log 10328 1812 Not Found: /favicon.ico
WARNING 2023-08-01 21:35:46,028 basehttp 10328 1812 "GET /favicon.ico HTTP/1.1" 404 2966
INFO 2023-08-01 21:36:12,225 basehttp 10328 1812 "GET /about HTTP/1.1" 301 0
INFO 2023-08-01 21:36:13,213 views 10328 4076 About page accessed
INFO 2023-08-01 21:36:13,215 basehttp 10328 4076 "GET /about/ HTTP/1.1" 200 309
INFO 2023-08-01 22:00:08,509 autoreload 12104 7684 Watching for file changes with StatReloader
INFO 2023-08-01 22:00:11,731 views 12104 15628 Index page accessed
ERROR 2023-08-01 22:00:12,327 log 12104 15628 Internal Server Error: /
Traceback (most recent call last):
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\project_one\firstapp\views.py", line 10, in index
    return render(request, 'firstapp/index.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\loader_tags.py", line 220, in do_block
    raise TemplateSyntaxError("'%s' tag takes only one argument" % bits[0])
django.template.exceptions.TemplateSyntaxError: 'block' tag takes only one argument
ERROR 2023-08-01 22:00:12,359 basehttp 12104 15628 "GET / HTTP/1.1" 500 158247
INFO 2023-08-01 22:03:51,502 views 12104 15628 About page accessed
INFO 2023-08-01 22:03:51,505 basehttp 12104 15628 "GET /about/ HTTP/1.1" 200 313
INFO 2023-08-01 22:03:59,043 views 12104 15628 Index page accessed
INFO 2023-08-01 22:03:59,045 basehttp 12104 15628 "GET / HTTP/1.1" 200 367
INFO 2023-08-01 22:04:08,799 views 12104 15628 About page accessed
INFO 2023-08-01 22:04:08,800 basehttp 12104 15628 "GET /about/ HTTP/1.1" 200 313
INFO 2023-08-01 22:56:34,377 autoreload 12004 13688 Watching for file changes with StatReloader
INFO 2023-08-01 22:56:37,305 views 12004 15248 Index page accessed
INFO 2023-08-01 22:56:37,314 basehttp 12004 15248 "GET / HTTP/1.1" 200 367
INFO 2023-08-01 22:56:58,359 basehttp 12004 15248 "GET /headsortails/10 HTTP/1.1" 301 0
ERROR 2023-08-01 22:56:58,459 log 12004 12572 Internal Server Error: /headsortails/10/
Traceback (most recent call last):
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py", line 21, in headsortails
    return render(request, 'secondapp/headsortails.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\base.py", line 484, in parse
    raise self.error(token, e)
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(result_list)' from 'len(result_list)'
ERROR 2023-08-01 22:56:58,472 basehttp 12004 12572 "GET /headsortails/10/ HTTP/1.1" 500 174854
INFO 2023-08-01 22:59:04,748 autoreload 12004 13688 K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py changed, reloading.
INFO 2023-08-01 22:59:05,827 autoreload 15944 4728 Watching for file changes with StatReloader
INFO 2023-08-01 22:59:07,930 basehttp 15944 15620 "GET /headsortails/10/ HTTP/1.1" 200 683
INFO 2023-08-01 22:59:20,028 basehttp 15944 15620 "GET /headsortails/10/ HTTP/1.1" 200 681
INFO 2023-08-01 22:59:30,070 basehttp 15944 15620 "GET /headsortails/30/ HTTP/1.1" 200 1481
INFO 2023-08-01 22:59:42,886 basehttp 15944 15620 "GET /dice/30/ HTTP/1.1" 200 1255
ERROR 2023-08-01 23:00:05,178 log 15944 15620 Internal Server Error: /randnumber/30/
Traceback (most recent call last):
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py", line 35, in randnumber
    result_list = [randint(0, 100) for i in range(o, number)]
                                                  ^
NameError: name 'o' is not defined
ERROR 2023-08-01 23:00:05,181 basehttp 15944 15620 "GET /randnumber/30/ HTTP/1.1" 500 67310
INFO 2023-08-01 23:01:03,127 autoreload 15944 4728 K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py changed, reloading.
INFO 2023-08-01 23:01:04,072 autoreload 15272 3408 Watching for file changes with StatReloader
INFO 2023-08-01 23:01:06,612 basehttp 15272 4144 "GET /randnumber/30/ HTTP/1.1" 200 1293
INFO 2023-08-06 19:10:42,879 autoreload 1896 1164 Watching for file changes with StatReloader
INFO 2023-08-06 19:11:07,323 autoreload 1896 1164 K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\urls.py changed, reloading.
INFO 2023-08-06 19:11:08,226 autoreload 2500 8928 Watching for file changes with StatReloader
INFO 2023-08-06 19:11:58,615 autoreload 2500 8928 K:\YandexDisk\razrab\Django\seminars\project_one\thirdapp\views.py changed, reloading.
INFO 2023-08-06 19:11:59,498 autoreload 10280 8868 Watching for file changes with StatReloader
INFO 2023-08-06 19:12:10,719 views 10280 11912 Index page accessed
INFO 2023-08-06 19:12:10,833 basehttp 10280 11912 "GET / HTTP/1.1" 200 367
WARNING 2023-08-06 19:12:11,908 log 10280 11912 Not Found: /favicon.ico
WARNING 2023-08-06 19:12:11,908 basehttp 10280 11912 "GET /favicon.ico HTTP/1.1" 404 3806
INFO 2023-08-06 19:12:25,429 basehttp 10280 14192 "GET /game_form HTTP/1.1" 301 0
ERROR 2023-08-06 19:12:26,045 log 10280 10188 Internal Server Error: /game_form/
Traceback (most recent call last):
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view secondapp.views.game_form didn't return an HttpResponse object. It returned None instead.
ERROR 2023-08-06 19:12:26,047 basehttp 10280 10188 "GET /game_form/ HTTP/1.1" 500 68050
INFO 2023-08-06 19:14:07,483 autoreload 10280 8868 K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py changed, reloading.
INFO 2023-08-06 19:14:08,450 autoreload 11556 6880 Watching for file changes with StatReloader
ERROR 2023-08-06 19:14:12,739 log 11556 11268 Internal Server Error: /game_form/
Traceback (most recent call last):
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view secondapp.views.game_form didn't return an HttpResponse object. It returned None instead.
ERROR 2023-08-06 19:14:12,743 basehttp 11556 11268 "GET /game_form/ HTTP/1.1" 500 68187
INFO 2023-08-06 19:16:08,267 autoreload 11556 6880 K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py changed, reloading.
INFO 2023-08-06 19:16:09,200 autoreload 2524 15448 Watching for file changes with StatReloader
INFO 2023-08-06 19:16:12,088 basehttp 2524 13788 "GET /game_form/ HTTP/1.1" 200 801
INFO 2023-08-06 19:16:27,387 views 2524 14192 Get game_type='dice', attempt_amount=20.
ERROR 2023-08-06 19:16:27,719 log 2524 14192 Internal Server Error: /game_form/
Traceback (most recent call last):
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py", line 24, in game_form
    dice(request='POST', number=attempt_amount)
  File "K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py", line 50, in dice
    return render(request, 'secondapp/dice.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\base.py", line 173, in render
    with context.bind_template(self):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\context.py", line 254, in bind_template
    updates.update(processor(self.request))
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\context_processors.py", line 41, in debug
    if settings.DEBUG and request.META.get("REMOTE_ADDR") in settings.INTERNAL_IPS:
                          ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'META'
ERROR 2023-08-06 19:16:27,729 basehttp 2524 14192 "POST /game_form/ HTTP/1.1" 500 103884
INFO 2023-08-06 19:17:11,671 autoreload 2524 15448 K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py changed, reloading.
INFO 2023-08-06 19:17:12,542 autoreload 10740 8456 Watching for file changes with StatReloader
INFO 2023-08-06 19:17:18,110 views 10740 12156 Get game_type='dice', attempt_amount=20.
ERROR 2023-08-06 19:17:18,179 log 10740 12156 Internal Server Error: /game_form/
Traceback (most recent call last):
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py", line 24, in game_form
    dice(number=attempt_amount)
TypeError: dice() missing 1 required positional argument: 'request'
ERROR 2023-08-06 19:17:18,183 basehttp 10740 12156 "POST /game_form/ HTTP/1.1" 500 69561
INFO 2023-08-06 19:17:33,280 basehttp 10740 8164 "GET /game_form/ HTTP/1.1" 200 801
INFO 2023-08-06 19:17:38,138 views 10740 12008 Get game_type='coin', attempt_amount=20.
ERROR 2023-08-06 19:17:38,175 log 10740 12008 Internal Server Error: /game_form/
Traceback (most recent call last):
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py", line 22, in game_form
    headsortails(number=attempt_amount)
TypeError: headsortails() missing 1 required positional argument: 'request'
ERROR 2023-08-06 19:17:38,178 basehttp 10740 12008 "POST /game_form/ HTTP/1.1" 500 69587
INFO 2023-08-06 19:18:56,454 autoreload 10740 8456 K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py changed, reloading.
INFO 2023-08-06 19:18:57,395 autoreload 6956 9236 Watching for file changes with StatReloader
INFO 2023-08-06 19:19:02,501 views 6956 15940 Get game_type='coin', attempt_amount=20.
ERROR 2023-08-06 19:19:02,643 log 6956 15940 Internal Server Error: /game_form/
Traceback (most recent call last):
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py", line 22, in game_form
    headsortails(request='GET', number=attempt_amount)
  File "K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py", line 41, in headsortails
    return render(request, 'secondapp/headsortails.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\base.py", line 173, in render
    with context.bind_template(self):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\context.py", line 254, in bind_template
    updates.update(processor(self.request))
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\context_processors.py", line 41, in debug
    if settings.DEBUG and request.META.get("REMOTE_ADDR") in settings.INTERNAL_IPS:
                          ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'META'
ERROR 2023-08-06 19:19:02,652 basehttp 6956 15940 "POST /game_form/ HTTP/1.1" 500 107740
INFO 2023-08-06 19:19:41,916 autoreload 6956 9236 K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py changed, reloading.
INFO 2023-08-06 19:19:45,041 autoreload 12928 7160 Watching for file changes with StatReloader
INFO 2023-08-06 19:22:00,309 autoreload 12928 7160 K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py changed, reloading.
INFO 2023-08-06 19:22:01,487 autoreload 724 13348 Watching for file changes with StatReloader
INFO 2023-08-06 19:23:04,910 autoreload 724 13348 K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py changed, reloading.
INFO 2023-08-06 19:23:05,808 autoreload 11940 10576 Watching for file changes with StatReloader
INFO 2023-08-06 19:23:12,803 views 11940 3388 Get game_type='coin', attempt_amount=20.
ERROR 2023-08-06 19:23:13,064 log 11940 3388 Internal Server Error: /game_form/
Traceback (most recent call last):
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py", line 22, in game_form
    headsortails(request.method, number=attempt_amount)
  File "K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py", line 41, in headsortails
    return render(request, 'secondapp/headsortails.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\base.py", line 173, in render
    with context.bind_template(self):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\context.py", line 254, in bind_template
    updates.update(processor(self.request))
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\context_processors.py", line 41, in debug
    if settings.DEBUG and request.META.get("REMOTE_ADDR") in settings.INTERNAL_IPS:
                          ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'META'
ERROR 2023-08-06 19:23:13,073 basehttp 11940 3388 "POST /game_form/ HTTP/1.1" 500 107725
INFO 2023-08-06 19:24:22,445 autoreload 11940 10576 K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py changed, reloading.
INFO 2023-08-06 19:24:23,367 autoreload 13788 14072 Watching for file changes with StatReloader
INFO 2023-08-06 19:24:28,797 views 13788 5592 Get game_type='coin', attempt_amount=20.
ERROR 2023-08-06 19:24:28,878 log 13788 5592 Internal Server Error: /game_form/
Traceback (most recent call last):
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view secondapp.views.game_form didn't return an HttpResponse object. It returned None instead.
ERROR 2023-08-06 19:24:28,881 basehttp 13788 5592 "POST /game_form/ HTTP/1.1" 500 69754
INFO 2023-08-06 19:25:09,819 autoreload 13788 14072 K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py changed, reloading.
INFO 2023-08-06 19:25:10,873 autoreload 8008 8556 Watching for file changes with StatReloader
INFO 2023-08-06 19:25:14,404 basehttp 8008 1952 "GET /game_form/ HTTP/1.1" 200 801
INFO 2023-08-06 19:25:20,407 views 8008 14220 Get game_type='coin', attempt_amount=5.
INFO 2023-08-06 19:25:20,418 basehttp 8008 14220 "POST /game_form/ HTTP/1.1" 200 820
INFO 2023-08-06 19:25:44,879 views 8008 12860 Get game_type='dice', attempt_amount=5.
INFO 2023-08-06 19:25:44,884 basehttp 8008 12860 "POST /game_form/ HTTP/1.1" 200 820
INFO 2023-08-06 19:27:21,182 autoreload 8008 8556 K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py changed, reloading.
INFO 2023-08-06 19:27:22,101 autoreload 8348 8820 Watching for file changes with StatReloader
INFO 2023-08-06 19:27:24,532 views 8348 9260 Get game_type='dice', attempt_amount=5.
ERROR 2023-08-06 19:27:24,606 log 8348 9260 Internal Server Error: /game_form/
Traceback (most recent call last):
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view secondapp.views.game_form didn't return an HttpResponse object. It returned None instead.
ERROR 2023-08-06 19:27:24,609 basehttp 8348 9260 "POST /game_form/ HTTP/1.1" 500 69753
INFO 2023-08-06 19:34:25,081 autoreload 8348 8820 K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py changed, reloading.
INFO 2023-08-06 19:34:26,067 autoreload 15024 7536 Watching for file changes with StatReloader
INFO 2023-08-06 19:34:31,516 views 15024 824 Get game_type='dice', attempt_amount=5.
ERROR 2023-08-06 19:34:31,653 log 15024 824 Internal Server Error: /game_form/
Traceback (most recent call last):
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py", line 24, in game_form
    dice(HttpRequest, number=attempt_amount)
  File "K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py", line 50, in dice
    return render(request, 'secondapp/dice.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\base.py", line 173, in render
    with context.bind_template(self):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\context.py", line 254, in bind_template
    updates.update(processor(self.request))
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\context_processors.py", line 41, in debug
    if settings.DEBUG and request.META.get("REMOTE_ADDR") in settings.INTERNAL_IPS:
                          ^^^^^^^^^^^^
AttributeError: type object 'HttpRequest' has no attribute 'META'
ERROR 2023-08-06 19:34:31,662 basehttp 15024 824 "POST /game_form/ HTTP/1.1" 500 103756
INFO 2023-08-06 19:36:16,817 autoreload 15024 7536 K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py changed, reloading.
INFO 2023-08-06 19:36:17,754 autoreload 5976 4872 Watching for file changes with StatReloader
INFO 2023-08-06 19:36:23,030 views 5976 8568 Index page accessed
INFO 2023-08-06 19:36:23,043 basehttp 5976 8568 "GET / HTTP/1.1" 200 367
INFO 2023-08-06 19:36:40,522 basehttp 5976 13144 "GET /game_form/ HTTP/1.1" 200 801
INFO 2023-08-06 19:36:44,563 views 5976 13144 Get game_type='coin', attempt_amount=5.
ERROR 2023-08-06 19:36:44,659 log 5976 13144 Internal Server Error: /game_form/
Traceback (most recent call last):
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py", line 22, in game_form
    headsortails(HttpResponse, number=attempt_amount)
  File "K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py", line 41, in headsortails
    return render(request, 'secondapp/headsortails.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\base.py", line 173, in render
    with context.bind_template(self):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\context.py", line 254, in bind_template
    updates.update(processor(self.request))
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\context_processors.py", line 41, in debug
    if settings.DEBUG and request.META.get("REMOTE_ADDR") in settings.INTERNAL_IPS:
                          ^^^^^^^^^^^^
AttributeError: type object 'HttpResponse' has no attribute 'META'
ERROR 2023-08-06 19:36:44,667 basehttp 5976 13144 "POST /game_form/ HTTP/1.1" 500 104590
INFO 2023-08-06 19:38:06,850 autoreload 5976 4872 K:\YandexDisk\razrab\Django\seminars\project_one\secondapp\views.py changed, reloading.
INFO 2023-08-06 19:38:08,026 autoreload 12416 14836 Watching for file changes with StatReloader
INFO 2023-08-06 19:38:13,728 views 12416 14592 Get game_type='coin', attempt_amount=5.
ERROR 2023-08-06 19:38:13,804 log 12416 14592 Internal Server Error: /game_form/
Traceback (most recent call last):
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view secondapp.views.game_form didn't return an HttpResponse object. It returned None instead.
ERROR 2023-08-06 19:38:13,807 basehttp 12416 14592 "POST /game_form/ HTTP/1.1" 500 69753
INFO 2023-08-06 20:31:06,167 autoreload 11164 9732 Watching for file changes with StatReloader
INFO 2023-08-06 20:31:08,767 views 11164 11516 Index page accessed
INFO 2023-08-06 20:31:08,775 basehttp 11164 11516 "GET / HTTP/1.1" 200 367
INFO 2023-08-06 20:31:21,141 basehttp 11164 6276 "GET /game_form/ HTTP/1.1" 200 801
INFO 2023-08-06 20:31:28,050 views 11164 6252 Get game_type='coin', attempt_amount=5.
INFO 2023-08-06 20:31:28,070 basehttp 11164 6252 "POST /game_form/ HTTP/1.1" 200 477
INFO 2023-08-07 18:27:11,107 autoreload 1664 14660 Watching for file changes with StatReloader
INFO 2023-08-07 18:27:33,969 autoreload 1664 14660 K:\YandexDisk\razrab\Django\seminars\project_one\thirdapp\urls.py changed, reloading.
INFO 2023-08-07 18:27:34,974 autoreload 7256 14104 Watching for file changes with StatReloader
INFO 2023-08-07 18:27:54,635 autoreload 7256 14104 K:\YandexDisk\razrab\Django\seminars\project_one\thirdapp\urls.py changed, reloading.
INFO 2023-08-07 18:27:55,543 autoreload 16372 4656 Watching for file changes with StatReloader
INFO 2023-08-07 18:28:00,966 views 16372 14816 Index page accessed
INFO 2023-08-07 18:28:03,187 basehttp 16372 14816 "GET / HTTP/1.1" 200 367
WARNING 2023-08-07 18:28:04,530 log 16372 14816 Not Found: /favicon.ico
WARNING 2023-08-07 18:28:04,530 basehttp 16372 14816 "GET /favicon.ico HTTP/1.1" 404 4162
INFO 2023-08-07 18:28:17,048 basehttp 16372 1380 "GET /author_add HTTP/1.1" 301 0
ERROR 2023-08-07 18:28:18,195 log 16372 1348 Internal Server Error: /author_add/
Traceback (most recent call last):
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'csrf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\project_one\thirdapp\views.py", line 19, in author_add
    return render(request, 'thirdapp/author_add.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 11: 'csrf'. Did you forget to register or load this tag?
ERROR 2023-08-07 18:28:18,217 basehttp 16372 1348 "GET /author_add/ HTTP/1.1" 500 135916
INFO 2023-08-07 18:34:02,118 autoreload 9616 11864 Watching for file changes with StatReloader
INFO 2023-08-07 18:34:23,126 basehttp 9616 12536 "GET /author_add/ HTTP/1.1" 200 1100
ERROR 2023-08-07 18:35:15,489 log 9616 2628 Internal Server Error: /author_add/
Traceback (most recent call last):
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\project_one\thirdapp\views.py", line 14, in author_add
    biography=form.cleaned_data['biography'],
              ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'biography'
ERROR 2023-08-07 18:35:15,492 basehttp 9616 2628 "POST /author_add/ HTTP/1.1" 500 69425
INFO 2023-08-07 18:42:44,485 autoreload 9616 11864 K:\YandexDisk\razrab\Django\seminars\project_one\thirdapp\forms.py changed, reloading.
INFO 2023-08-07 18:42:45,683 autoreload 8300 13976 Watching for file changes with StatReloader
INFO 2023-08-07 18:47:40,172 autoreload 8300 13976 K:\YandexDisk\razrab\Django\seminars\project_one\thirdapp\forms.py changed, reloading.
INFO 2023-08-07 18:47:41,363 autoreload 8972 1620 Watching for file changes with StatReloader
INFO 2023-08-07 18:47:53,117 basehttp 8972 5628 "GET /author_add/ HTTP/1.1" 200 1267
ERROR 2023-08-07 18:48:46,640 log 8972 8256 Internal Server Error: /author_add/
Traceback (most recent call last):
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view thirdapp.views.author_add didn't return an HttpResponse object. It returned None instead.
ERROR 2023-08-07 18:48:46,643 basehttp 8972 8256 "POST /author_add/ HTTP/1.1" 500 70208
INFO 2023-08-07 18:53:51,730 autoreload 8972 1620 K:\YandexDisk\razrab\Django\seminars\project_one\thirdapp\views.py changed, reloading.
INFO 2023-08-07 18:53:53,101 autoreload 7424 828 Watching for file changes with StatReloader
INFO 2023-08-07 18:58:53,860 autoreload 7424 828 K:\YandexDisk\razrab\Django\seminars\project_one\thirdapp\views.py changed, reloading.
INFO 2023-08-07 18:58:55,177 autoreload 6392 2756 Watching for file changes with StatReloader
INFO 2023-08-07 18:59:14,263 basehttp 6392 7312 "POST /author_add/ HTTP/1.1" 200 69
INFO 2023-08-07 18:59:27,279 basehttp 6392 6604 "GET /author_add/ HTTP/1.1" 200 1267
INFO 2023-08-07 19:00:27,415 basehttp 6392 15468 "POST /author_add/ HTTP/1.1" 200 67
INFO 2023-08-07 19:00:42,995 basehttp 6392 5052 "POST /author_add/ HTTP/1.1" 200 67
INFO 2023-08-07 19:00:49,667 basehttp 6392 14180 "GET /author_add/ HTTP/1.1" 200 1267
INFO 2023-08-07 19:02:00,714 basehttp 6392 6556 "POST /author_add/ HTTP/1.1" 200 75
INFO 2023-08-07 19:02:24,792 basehttp 6392 8520 "GET /article_add/ HTTP/1.1" 200 1082
ERROR 2023-08-07 19:03:00,276 log 6392 7256 Internal Server Error: /article_add/
Traceback (most recent call last):
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\YandexDisk\razrab\Django\seminars\project_one\thirdapp\views.py", line 29, in article_add
    content=form.cleaned_data['content'],
            ~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'content'
ERROR 2023-08-07 19:03:00,281 basehttp 6392 7256 "POST /article_add/ HTTP/1.1" 500 69417
